### ISSUE TITLE
Scaling not great?

### ISSUE THREAD

**Issue by francisdb** [vpinball/libdmdutil#2]
https://github.com/PPUC/libzedmd/issues/13 mentions that the issue is probably here?

This is Baywatch:

192x64 rendered to 128*32

* Could scaling be improved? Is nearest neighbor in use?
* I wonder if stretching to the full space would be a good idea?

![image](https://github.com/vpinball/libdmdutil/assets/161305/61e4dcd4-b65d-4f64-b92e-96470615def2)

**Comment by toxieainc** [comment]
When i last looked at the code, some scaling code was using bilinear lookups, but this will only have a positive effect when upscaling. For downscaling, one must do an averaging of the downscaled pixels.
The problem is that with these very low resolutions and non-integer scalings, the result will also suck.
So what i did for pinmame (when adapting the external dmd driver code) was to downscale in y-direction via averaging (to go from 192x64 to 192x32 by averaging 2 rows into one) and then only averaging 2/3s of the pixels in x-direction, and leaving 1/3 untouched/as-is (to go to 128x32). Also not optimal, but was the best tradeoff in my experiments.

**Comment by jsm174** [comment]
Scaling / aspect Rratio centering is only for Pixelcade which we do in this library. I added it at the last moment as I realized some games would not work on it. I'm no expert on this topic 😄 

@francisdb is showing a ZeDMD device I believe, and ZeDMD firmware and or libzedmd handles all the scaling.

@mkalkbrenner could elaborate on this more

**Comment by jsm174** [comment]
All I can say is if you look at the code in this repo, there is no scaling done on the frame for the zedmd path.
